name: Deploy Service

on:
  push:
    branches:
     - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r torch-requirements.txt
        pip install -r requirements.txt

    - name: Run unit tests
      run: python -m unittest discover -s tests -p "test_*.py"

    - name: Run tests with coverage
      run: |
        pytest --cov=app.py --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        
  deploy:
    needs: test  # Wait for test job to succeed
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ubuntu/YoloService || (git clone https://github.com/MarwanHalabi/YoloService.git && cd YoloService)
          git pull origin main
          
          # Replace with your desired Python version
          PYTHON_VERSION=3.12.6
          VENV_NAME=venv3126

          # Create virtualenv only if it doesn't exist
          if ! pyenv virtualenvs --bare | grep -q "^$VENV_NAME$"; then
            pyenv install -s "$PYTHON_VERSION"
            pyenv virtualenv "$PYTHON_VERSION" "$VENV_NAME"
          fi

          # Activate it
          pyenv activate "$VENV_NAME"

          # Install deps
          pip install -r torch-requirements.txt
          pip install -r requirements.txt

          # Restart service
          sudo systemctl restart yolo.service