name: Deploy Service

on:
  push:
    branches:
     - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: HOST
        username: ubuntu
        key: SSH_KEY
        script: |
          cd /home/ubuntu/YoloService || (git clone https://github.com/MarwanHalabi/YoloService.git && cd YoloService)
          git pull origin main
          
          # Load pyenv
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"

          # Activate your env (replace with your actual env name if different)
          pyenv activate venv3126

          # Install deps
          pip install -U pip
          pip install -r torch-requirements.txt
          pip install -r requirements.txt

          # Restart service
          sudo systemctl daemon-reexec
          sudo systemctl daemon-reload
          sudo systemctl restart yolo.service
          sudo systemctl status yolo.service --no-pager