name: Deploy Service

on:
  push:
    branches:
     - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: HOST
        username: ubuntu
        key: SSH_KEY
        script: |
          cd /home/ubuntu/YoloService || (git clone https://github.com/MarwanHalabi/YoloService.git && cd YoloService)
          
          # YOUR CODE HERE ... 
          #  - get the updated code version from github
          #  - install venv and dependencies if needed
          #  - set up the Linux service