name: Deploy Service

on:
  push:
    branches:
     - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: HOST
        username: ubuntu
        key: SSH_KEY
        script: |
          cd /home/ubuntu/YoloService || (git clone https://github.com/MarwanHalabi/YoloService.git && cd YoloService)
          git pull origin main
          
          # Replace with your desired Python version
          PYTHON_VERSION=3.12.6
          VENV_NAME=venv3126

          # Create virtualenv only if it doesn't exist
          if ! pyenv virtualenvs --bare | grep -q "^$VENV_NAME$"; then
            pyenv install -s "$PYTHON_VERSION"
            pyenv virtualenv "$PYTHON_VERSION" "$VENV_NAME"
          fi

          # Activate it
          pyenv activate "$VENV_NAME"

          # Install deps
          pip install -r torch-requirements.txt
          pip install -r requirements.txt

          # Restart service
          sudo systemctl restart yolo.service